title: Mon Site Web Statique
description: Site pour tester le déploiement sur GitHub Pages.
baseurl: "test_site_static/" # Laisser vide si le site est à la racine du domaine
url: "https://godefroyl.github.io/" # Remplacez par l'URL de votre site
